export const AUTH_ERROR = 'AUTH_ERROR'
export const IS_AUTH = 'IS_AUTH'
export const IS_LOADING = 'IS_LOADING'
export const USER_DATA = 'USER_DATA'
export const IS_POPUP = 'IS_POPUP'
export const AUTH_CLIENT = 'AUTH_CLIENT'
export const RESET_AUTH = 'RESET_AUTH'
