export const TOGGLE_DARK = 'CHANGE_THEME'
export const SHARE_LINK = 'SHARE_LINK'
export const IS_MOBILE = 'IS_MOBILE'
export const IS_DRAWING = 'IS_DRAWING'
export const LOCATE_USER = 'LOCATE_USER'
export const CURRENT_SELECTION = 'CURRENT_SELECTION'
