export const CURRENT_SELECTION = 'map/CURRENT_SELECTION'
export const CURRENT_MAP_FILTER = 'map/CURRENT_MAP_FILTER'
export const MAP_BOUNDS = 'map/MAP_BOUNDS'
export const MAP_FOCUS_ON = 'map/MAP_FOCUS_ON'
export const MAP_POINTS = 'map/MAP_POINTS'
