<template>
  <div
    class="main-wrapper pt20 pb20 flex justify-content-center column align-items-center"
  >
    <div class="inner-wrapper">
      <h1 class="text-center title-variant">
        Premium Partners & Exclusive Sponsors
      </h1>
      <el-card :class="{ dark }" shadow="never" class="p4 mt12">
        <p>
          Premium Partners and Exclusive Sponsors allow Infrapedia to keep
          providing the world’s most realistic view of the internet
          infrastructure for free by assuring the long term sustainability of
          our platform and community.
        </p>
        <p>
          Benefits of becoming Infrapedia’s sponsor or partner:
        </p>
        <div class="ml2">
          <p>
            Through our live map, multiple social media channels and Infrapedia
            Live streams, we are constantly reaching out to an ever-growing
            audience of industry professionals. Becoming a partner or sponsor
            gives you a unique opportunity for your brand to be highlighted all
            throughout our Infrapedia platforms.
          </p>
          <p>
            As an Exclusive Sponsor your brand will be shown on prominent spots
            on the map, immediately visible for every user, in our newsletters
            and videos.
          </p>
          <p>
            As a Premium Partner your brand will be shown on our website and you
            will be the only one to receive a notification of any relevant Buy
            Now! sales leads generated by users on our platform on an asset
            where you have presence. This unique feature of our interactive map
            allows users to submit their request for data center space,
            terrestrial fiber or subsea capacity to Infrapedia and its partners.
          </p>
        </div>
        <p>
          For more information about sponsorships or partnerships, contact us:
          <a href="mailto:admin@infrapedia.com">admin@infrapedia.com</a>
        </p>
      </el-card>
    </div>
  </div>
</template>

<script>
export default {
  name: 'SponsorsPage',
  head: {
    title:
      'Infrapedia | Exclusive Sponsorships | Global Internet Infrastructure Map',
    meta: [
      {
        name: 'application-name',
        content:
          'Infrapedia | Exclusive Sponsorships | Global Internet Infrastructure Map'
      },
      {
        name: 'description',
        content:
          'Infrapedia is the world’s largest crowd-sourced Live Map of the Global Internet Infrastructure. Be one of our Exclusive Sponsors and be everywhere we are.'
      },
      {
        name: 'keywords',
        content:
          'custom maps, fiber optics maps, internet infrastructure map, live map, consulting, data center, sponsorship, ads, telecommunications'
      }
    ]
  },
  computed: {
    dark() {
      return this.$store.state.isDark
    }
  },
  beforeCreate() {
    this.$emit('layout', 'landing-layout')
  }
}
</script>

<style lang="scss" scoped>
@import '../assets/scss/pages/sponsors-styles.scss';
</style>
