<template>
  <div
    class="main-wrapper pt20 pb20 flex justify-content-center column align-items-center"
  >
    <div class="inner-wrapper">
      <h1 class="text-center title-variant">
        Premium Partners & Sponsors
      </h1>
      <el-card :class="{ dark }" shadow="never" class="p4 mt12 no-border">
        <p>
          Premium Partners and Sponsors are valued by us because they allow
          Infrapedia to stay committed to continuously work on new tools for the
          community and further expand the map and services portfolio to anyone
          who needs it.
        </p>
        <p>
          Becoming a partner or sponsor gives you a unique opportunity for your
          brand to be highlighted all throughout our Infrapedia platforms.
        </p>
        <p>
          As a Sponsor your brand will be shown on prominent spots on the map,
          immediately visible for every user, in our newsletters and videos.
        </p>
        <p>
          As a Premium Partner your brand will be shown on our website and you
          will be the only one to receive a notification of any relevant Buy
          Now! sales leads generated by users on our platform.
        </p>
        <p>
          For more information about sponsorships or partnerships, contact us:
          <a href="mailto:admin@infrapedia.com">admin@infrapedia.com</a>
        </p>
      </el-card>
      <div class="p4 mb20 mt12" id="partnersSection">
        <h2 class="title--homepage-variant mb20 text-center diff">
          Join Our Partners
        </h2>
        <div class="boxes-wrapper">
          <div class="el-card box p2" v-for="(partner, i) in premium" :key="i">
            <el-image fit="contain" :src="partner.logo" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'SponsorsPage',
  head: {
    title:
      'Infrapedia | Exclusive Sponsorships | Global Internet Infrastructure Map',
    meta: [
      {
        name: 'application-name',
        content:
          'Infrapedia | Exclusive Sponsorships | Global Internet Infrastructure Map'
      },
      {
        name: 'description',
        content:
          'Infrapedia is the world’s largest crowd-sourced Live Map of the Global Internet Infrastructure. Be one of our Exclusive Sponsors and be everywhere we are.'
      },
      {
        name: 'keywords',
        content:
          'custom maps, fiber optics maps, internet infrastructure map, live map, consulting, data center, sponsorship, ads, telecommunications'
      }
    ]
  },
  computed: {
    dark() {
      return this.$store.state.isDark
    },
    premium() {
      return this.$store.state.premium
    }
  },
  beforeCreate() {
    this.$emit('layout', 'landing-layout')
  },
  async mounted() {
    await this.$store.dispatch('getPremiumData')
  }
}
</script>

<style lang="scss" scoped>
@import '../assets/scss/pages/sponsors-styles.scss';
</style>
