export const EDITOR_LOAD_DRAW = 'editor-load-draw'
export const EDITOR_FILE_CONVERTED = 'kmz-file-converted'
export const EDITOR_SET_FEATURES = 'editor-set-features'
export const EDITOR_SET_FEATURES_LIST = 'editor-set-features-list'
export const EDITOR_GET_FEATURES_LIST = 'editor-get-features-list'
export const SET_MAP_SOURCES = 'set-map-sources'
