export const DRAWING = 'drawing'
export const TOGGLE_THEME = 'TOGGLE_DARK'
export const CABLE_SELECTED = 'cable-selected'
export const TITLE_BY_SELECTION = 'title-by-selection'
export const CLEAR_SELECTION = 'clear-selection'
export const BUY_CAPACITY = 'buy-capacity'
export const EDIT_CABLE = 'edit-cable'
