export const steps = {
  0: [
    'Alaska United - East',
    'ANTILLAS I',
    'ATLANTIS-2',
    'ASE (Asia-Submarine Express)',
    'APHRODITE-2',
    'Amerigo Vespucci',
    'Australia-Singapore Cable',
    'ARCOS-1',
    'AAE-1 (Asia Africa Europe)',
    'APG (Asia-Pacific Gateway)',
    'Australia-Japan Cable',
    'Africa-1',
    'Atisa',
    'AEConnect-1 (AEC-1)',
    'Avassa',
    'ARSAT',
    'AUTA (Alaska United Turnagain Arm)',
    'Aden-Djibouti',
    'Aqualink',
    'APNG-2 (Australia-Papua New Guinea-2)',
    'Asia Pacific Gateway (APG)',
    'Alaska United Southeast',
    'Alaska United - West',
    'Alonso de Ojeda',
    'ASH (American Samoa - Hawaii)',
    'Americas-1 North',
    'Americas II',
    'Atlas Offshore',
    'AAG (Asia-American Gateway)',
    'America Movil-1 (AMX-1)',
    'Azores Fiber Optic System (AFOS)',
    'AC-2 (Atlantic Crossing 2)',
    'APCN',
    'Alexandros',
    'Antilles Crossing',
    'ALETAR',
    'ALBA-1',
    'ADRIA-1',
    'ALPAL-2',
    'APCN2',
    'Airtel Mumbai',
    'Atlantic Crossing 1 (AC-1)',
    'Ariane 2',
    'Americas-1 South',
    'ACE (Africa Coast to Europe)',
    'ARBR (Argentina-Brazil)',
    'APX West',
    'AKORN Alaska-Oregon',
    'AeroNet',
    'Amerigo Vespucci',
    'America Movil Submarine Cable System-1 (AMX-1)',
    'AURORA Cable System',
    'Australia-Papua New Guinea-2 (APNG-2)',
    'Alaska United West',
    'ACS Alaska-Oregon Network (AKORN)',
    'America Movil-Telxius West Coast Cable ',
    'Apollo',
    'BBG (Bay of Bengal Gateway)',
    'BERYTAR',
    'BT-MT1',
    'Brazilian Festoon',
    'Borikén Submarine Cable System (BSCS)',
    'BKK Digitek',
    'BR-USA',
    'BT-Highlands and Islands Submarine Cable System',
    'BSCS (Batam Singapore Cable System)',
    'Boracay-Palawan Submarine Cable System',
    'Bharat Lanka Cable System',
    'BUGIO',
    'Bass Strait-1',
    'BRCS (Batam-Rengit Cable System)',
    'BDM (Batam Dumai Melaka Cable System)',
    'Baltic Sea Submarine Cable',
    'Bicentenario',
    'BDNSi (Bahamas Domestic Submarine Network)',
    'BAHAMAS-2',
    'BICS (Bahamas Internet Cable System )',
    'BALTICA',
    'BARSAV',
    'BCS East',
    'BCS North II',
    'Botnia',
    'BCS East-West Interlink',
    'BCS North I',
    'Balkans-Italy Network',
    'BT-Manx NI',
    'Bass Strait-2',
    'BtoBE (Bay to Bay Express Cable System)',
    'BP Fiber Backbone',
    'BRICS Cable',
    'BSFOCS',
    'BASICS (Batam Sarawak Internet Cable System)',
    'Bodo-Rost Cable',
    'Buffalo-Toronto Cable',
    'BlueMed',
    'Basslink',
    'BALOK',
    'B3JS (Jakarta-Bangka-Bintan-Batam-Singapore)',
    'BERYTAR',
    'Botnia',
    'Bahamas Domestic Submarine Network (BDSNi)',
    'Celtic',
    'CORSAR (Corsica- Sardinia)',
    'CANTAT-3',
    'CIRCE South',
    'CIRCE North',
    'Concerto',
    'Corse-Continent 4 (CC4)',
    'Corse-Continent 5 (CC5)',
    'CBUS (Caribbean-Bermuda U.S.)',
    'CanaLink',
    'C-Lion',
    'CADMOS',
    'COLUMBUS II',
    'CIOS',
    'COLUMBUS III',
    'CUCN',
    'Curie',
    'CARCIP (Caribbean Regional Communications Infrastructure Program)',
    'CSCS (Coral Sea Cable System)',
    'Chuuk-Pohnpei Cable',
    'Cobra Cable',
    'CC-2 (CeltixConnect-2)',
    'Crown Castle Milwaukee',
    'Chennai-Andaman & Nicobar Islands Cable',
    'Comoros Domestic Cable System',
    'CAM Ring',
    'Cross Straits Cable Network',
    'CB-1 (Challenger Bermuda-1)',
    'CANUS-1',
    'Corfu-Bar',
    'CC-1 (CeltixConnect-1)',
    'Caucasus Cable System',
    'Cayman-Jamaica',
    'CFX-1',
    'Celtic Norse',
    'Channel Islands-9 Liberty Submarine Cable',
    'Challenger Bermuda-1 (CB-1)',
    'Ceiba-2',
    'Cabo Verde Telecom Domestic Submarine Cable Phase 2',
    'Cabo Verde Telecom Domestic Submarine Cable Phase 1',
    'Ceiba-1',
    'Cabo Verde Telecom Domestic Submarine Cable Phase 3',
    'Dhiraagu Cable Network',
    'Danice',
    'Djibouti Africa Regional Express 1 (DARE1)',
    'Danica South',
    'Denmark-Poland 2',
    'Danica North',
    'Denmark-Sweden 15',
    'Denmark-Sweden 16',
    'Denmark-Germany 2',
    'Denmark-Norway 6',
    'Denmark-Norway 5',
    'Dumai-Melaka',
    'Diamond Cable',
    'DMCS (Dumai Medan Cable System)',
    'Denmark Global Connect',
    'Dhiraagu-SLT Submarine Cable Network',
    'Didon',
    'Denmark-Sweden 16',
    'Denmark-Sweden 18',
    'Denmark-Sweden 17',
    'Dumai-Melaka Cable System',
    'Dunant',
    'Estepona-Tetuan',
    'EESF-3 (Finland--Estonia 3)',
    'EESF-2 (Finland-Estonia 2)',
    'Estonia-Sweden 1',
    'ESAT 2',
    'ESAT 1',
    'Emerald Bridge Fibres',
    'EAC',
    'ECFS (Eastern Caribbean Fiber System)',
    'Energinet Laeso-Lyngsa',
    'Energinet Varberg-Laeso',
    'EE-S 1 (Sweden-Estonia)',
    'England Cable',
    'EASSY (Eastern Africa Submarine System)',
    'E-LLAN',
    'EllaLink',
    'ECLink',
    'EAC-C2C',
    'EIG (Europe India Gateway)',
    'East-West Submarine Cable System',
    'Eastern Light',
    'East-West',
    'Equiano',
    'Elektra-GlobalConnect 1 (GC1)',
    'Fehmarn Blt',
    'FA-1 (FLAG Atlantic)',
    'Fibralink',
    'FEA (FLAG Europe Asia)',
    'FOG (Fibre Optic Gulf)',
    'FALCON (FLAG Alcatel-Lucent Optical Network)',
    'FNAL (FLAG North Asia Loop)',
    'FARLAND',
    'FLAG ATLANTIC NORTH',
    'Far East Submarine Cable System',
    'Flores-Covo Cable System',
    'Fibra Optica Austral',
    'FLYLION3',
    'FEC (Finland Estonia Connection)',
    'FOS Quellon-Chacabuco',
    'Farland North',
    'FASTER',
    'Flores-Corvo Cable System',
    'FLAG North Asia Loop/REACH North Asia Loop',
    'Fiber Optic Gulf (FOG)',
    'Germany-Denmark 3',
    'Germany-Denmark 2',
    'GCN (Global Carribean Network)',
    'Gondwana-1',
    'GlobeNet',
    'GTT Express',
    'Greenland Connect',
    'G-P',
    'Gulf of California Cable',
    'GO-1 Mediterranean Cable System',
    'GTMO-PR',
    'GTMO-1',
    'Glo-2',
    'Greenland Connect North',
    'GTT Atlantic',
    'Gulf2Africa (G2A)',
    'Gemini',
    'GLO1',
    'Georgia-Russia',
    'Guernsey-Jersey-4',
    'Geo-Eirgrid',
    'GBICS /MENA (Gulf Bridge International Gulf Bridge International Cable System/Middle East North Africa Cable System)',
    'GO-1 Mediterranean Cable System',
    'Guam Okinawa Kyushu Incheon (GOKI)',
    'GlobeNet',
    'HSCS (Hokkaido-Sakhalin Cable System)',
    'HANNIBAL',
    'HANTRU-1',
    'HUGO',
    'HONOTUA Domestic',
    'HONOTUA International',
    'HAWK',
    'Hawaiki',
    'HK-G',
    'Hong Kong-Americas (HKA)',
    'H2 Cable',
    'HIFN (Hawaii Island Fibre Network)',
    'HICS (Hawaii Inter-Island Cable System)',
    'HANNIBAL System',
    'Havfrue/AEConnect-2(AEC-2)',
    'Hawaiki New',
    'Hainan-Hong Kong Submarine Cable System',
    'INGRID',
    'Interchange Cable Network 1 (ICN1)',
    'Italy-Albania',
    'Italy-Greece 1',
    'Italy-Libya',
    'Islalink',
    'I2ICN (i2i  Cable Network)',
    'ITUR',
    'Italy-Croatia',
    'Italy-Malta',
    'Italy-Monaco',
    'IOX Cable',
    'IGG (Indonesia Global Gateway)',
    'IFC-1 (Ireland-France Cable-1)',
    'Isles of Scilly Cable',
    'INDIGO-Central',
    'Interchange Cable Network 2 (ICN2)',
    'INDIGO-West',
    'Indonesia Connect by Telkom Indonesia',
    'IP-Only Denmark-Sweden',
    'IMEWE',
    'International Gateway (IGW)',
    'JAKABARE',
    'JONAH',
    'JUS (Japan-U.S. Cable Network)',
    'JBCS (Java Bali Cable System)',
    'JGA-S (Japan-Guam-Australia South)',
    'JAYABAYA (Jakarta Surabaya Cable System)',
    'Jupiter',
    'JGA-N (Japan-Guam-Australia North)',
    'Junior',
    'JIBA (Jambi-Batam Cable System)',
    'JaKa to LaDeMa',
    'Japan Information Highway (JIH)',
    'Janna',
    'Jerry Newton',
    'Kodiak Kenai',
    'KJCN (Korea-Japan Cable Network)',
    'Kuwait-Iran',
    'Kategat-1',
    'KELTRA-2 (Trapani-Kelibia)',
    'KAFOS',
    'KINYRAS',
    'Kanawa',
    'Kumul Domestic Submarine Cable System',
    'KKFL (Kodiak Kenai Fiber Link)',
    'Kattegat 1',
    'Kerch Strait Cable',
    'Kuwait-Iran',
    'Kattegat 2',
    'KetchCan1 Submarine Fiber Cable System',
    'LIME',
    'LION2',
    'LANIS 1',
    'LANIS 2',
    'Loukkos',
    'Lev Submarine System',
    'Labuan-Brunei Cable',
    'Lynn Canal Fiber',
    'LANIS-3',
    'Libreville-Port Gentil Cable',
    'LION Lower Indian Ocean Network',
    'La Runion Numrique',
    'LV-SE 1 (Latvia-Sweden 1)',
    'Lazaro Cardenas-Manzanillo Santiago Submarine Cable System (LCMSSCS)',
    'MainOne',
    'Maple Leaf Fibre',
    'Matrix Cable System',
    'Med Cable',
    'Melita-1',
    'MAC (Mid-Atlantic Crossing)',
    'MIC-1 (Moratelindo International Cable)',
    'Moratelindo Batam Dumai Cable (MBDC)',
    'Mataram Kupang Cable System (MKCS)',
    'MONET',
    'MENA (Middle East North Africa)',
    'MCT Cable System',
    'MAYA-1',
    'Malta-Italy Cable',
    'MALBEC',
    'Malta-Gozo Cable',
    'MARS (Mauritius and Rodrigues Submarine Cable System)',
    'MINERVA',
    'MedNautilus',
    'METISS (Meltingpot Indianoceanic Submarine System)',
    'MAREA',
    'MCT (Malaysia-Cambodia-Thailand) Cable',
    'Mariana-Guam Cable',
    'Miyazaki-Okinawa Cable (MOC)',
    'Moratelindo International Cable System-1 (MIC-1)',
    'Manatua',
    'Mandji Fiber Optic Cable',
    'NordBaltEurope',
    'NYNJ-1',
    'NATITUA',
    'NSC (North Sea Connect)',
    'NorSea Com 1',
    'NOR5KE',
    'Nationwide Submarine Cable Ooredoo Maldives (NaSCOM)',
    'Northern Lights',
    'NCSCS (Nigeria Cameroon Submarine Cable System)',
    'North West Cable System',
    'New Cross Pacific (NCP) Cable System',
    'NDTN (National Digital Transmission Network)',
    'Nelson-Levin',
    'NorthStar',
    'NordBalt',
    'Nunavut Undersea Fibre Optic Network System',
    'Okinawa Cellular Cable',
    'OTEGLOBE Kokkini-Bari',
    'OMRAN/EPEG Cable System',
    'Orient Express',
    'Oran-Valencia (ORVAL)',
    'Prat',
    'PAC (Pan-American Crossing)',
    'Pangea North',
    'Pangea South',
    'Pangea Baltic Loop',
    'Pencan-6',
    'PCCS',
    'POI (Pishgaman Oman Iran)',
    'Pasuli',
    'Polar Circle',
    'PENBAL-5',
    'Paniolo Cable Network',
    'Palapa Ring',
    'PEACE Cable',
    'PNG LNG',
    'PC-1',
    'PAN-AM (Pan American)',
    'Pencan9',
    'PLCN (Pacific Light Cable Network)',
    'PLDT Domestic Fiber Optic Network',
    'Picot-1',
    'Palawa-Iloilo Cable System',
    'PPC-1 (PIPE Pacific Cable-1)',
    'Persona',
    'PPC-1',
    'POSEIDON',
    'Pishgaman Oman Iran (POI) Network',
    'Palapa Ring West',
    'PGASCOM',
    'Pencan-8',
    'Qatar-UAE Submarine Cable System',
    'Quintillion Subsea Cable Network',
    'RIOJA-3',
    'Russia-Japan Cable Network (RJCN)',
    'Ronne Cable',
    'RJK',
    'RNAL',
    'SEACOM',
    'Strategic Evolution Underwater Link (SEUL)',
    'Scandinavian Ring North',
    'Scotland-Northern Ireland 2',
    'Seabras-1',
    'SJC2 (Southeast Asia-Japan Cable 2)',
    'SLT-Dhiraagu',
    'SMPR-1 (Saint Maarten Puerto Rico Network One)',
    'SAS-1 (Saudi Arabia-Sudan-1)',
    'Scandinavian Ring South',
    'SAC (South American Crossing)',
    'Svalbard Undersea Cable System',
    'SG-SCS (Suriname-Guyana)',
    'SFS-4 (Finland-Sweden 4)',
    'SFL (Sweden-Finland Link)',
    'Sirius North',
    'SEAS',
    'Sirius South',
    'SHEFA-2',
    'SAT-3',
    'SEAK',
    'Silphium',
    'SACS',
    'SJC',
    'SEA-ME-WE-5',
    'SAFE',
    'SIGMAR (Singapore Mynmar)',
    'SSSFOIP ( Sorsogon Samar Submarine Fiber Optical Interconnection Project )',
    'SAC/LAN (South American Crossing /Latin American Nautilus)',
    'St. Pierre and Miquelon Cable',
    'Sakhalin-Kuril Islands Cable',
    'SABR (South Africa-Brazil)',
    'SFS-4 (Sweden-Finland 4)',
    'Southern Cross NEXT',
    'SOLAS',
    'Skagerrak 4',
    'SAIL',
    'SAIT (San Andres Isla Tolu) Cable',
    'SRG-1 (Silk Route Gateway)',
    'SKR1M (Sistem Kabel Rakyat 1Malaysia)',
    'SAm-1',
    'Swansea-Brean',
    'Segunda FOS Canal de Chacao',
    'Saba, Statia Cable System (SSCS)',
    'SEA-US',
    'SEA-ME-WE-4',
    'Scotland-Northern Ireland 1',
    'St. Thomas-St. Croix System',
    'SEA-ME-WE 3',
    'Sweden-Latvia',
    'Skagenfier East',
    'Skagenfiber West',
    'SCCN (Southern Cross Cable Network)',
    'SAS (Samoa - American Samoa)',
    'SAT-2',
    'SxS',
    'SEAX-1 (SEA Cable Exchange-1)',
    'SAex',
    'SAEx2 (South Asia Express)',
    'STI Birmingham Network',
    'Scotland-Northern Ireland 1',
    'STI Pascagoula Network',
    'STI Jacksonville Network',
    'Saudi Arabia-Sudan-2 (SAS-2)',
    'sea2shore',
    'Subcan Link 2',
    'Subcan Link 1',
    'São Sebastião, Brazil',
    'Tampnet Offshore FOC Network',
    'TAT-14',
    'Trinidad-Curaco',
    'Tasman-2',
    'TGN-IA (Tata TGN Intra-Asia)',
    'T-V-H (Thailand-Vietnam-Hong Kong)',
    'TIS (Thailand-Indonesia-Singapore)',
    'TWA-1 (Transworld)',
    'Telstra Bass Strait 1',
    'Tangerine',
    'TGN Western Europe',
    'TGN Northern Europe',
    'TURCYOS-1',
    'TURCYOS-2',
    'TGN-Gulf',
    'TURMEOS-1',
    'Tamares Telecom',
    'Tasman Global Access',
    'TAGIDE-2',
    'TSE-1',
    'Tonga-Fiji',
    'TEAMs (The East African Marine System)',
    'Tverrlinken',
    'TCDE (Tonga Domestic Cable Extension)',
    'TERRA-Aleutian',
    'Taino-Carib',
    'Tannat',
    'Tui-Samoa',
    'TT-1',
    'TPC-5CN',
    'TRANSCAN-3',
    'Trapani-Kelibia',
    'TIISCS (Tata Indicom)',
    'TPE (Trans-Pacific Express)',
    'TGN Transpacific',
    'Telstra Endeavour',
    'TE North/TGN-Eurasia/SEACOM/Alexandros/Medex',
    'Turcyos-1',
    'Tamares North',
    'TimeWarner',
    'Taba-Aqaba',
    'Tanjun Pandan-Sungai Kakap Cable System',
    'Tobrok-Emasaed Cable System',
    'Telstra Endeavour',
    'TERRA SW',
    'Tata TGN Atlantic',
    'Ultramar GE',
    'UNISUR',
    'Unity/EAC-Pacific',
    'ULYSSES',
    'ULYSSES 2',
    'UGARIT',
    'UK-Channel Isles 7',
    'UAE-Iran',
    'UK-Netherlands 14',
    'UK-Belgium (Pan European Crossing)',
    'UK-Ireland (Pan European Crossing)',
    'UK-Channel Islands-8',
    'UK-Channel Islands-7',
    'Unity/EAC-Pacific',
    'Ventspils-Farosund-Stockholm',
    'VMSCS (Vodafone Malta-Sicily Cable System)',
    'Venezuela Festoon',
    'WALL-LI',
    'WARF',
    'WACS (West African Cable System)',
    'XL Axiata Indonesia Connect',
    'Yellow (AC-2)',
    'Zayo'
  ],
  1: [
    'Amsterdam Internet Exchange (AMS-IX)',
    'Brazil Internet Exchange (IX.br)',
    'BBIX',
    'Coresite Any2 Los Angeles',
    'Deutscher Commercial Internet Exchange (DE-CIX)',
    'Equinix Exchange',
    'France-IX',
    'FL-IX',
    'Hong Kong Internet eXchange (HKIX)',
    'Japan Network Access Point (JPNAP)',
    'JPIX',
    'London Internet Exchange (LINX)',
    'MKS-IX',
    'NetIX',
    'Neutral Internet Exchange (NL-ix)',
    'Netnod Internet Exchange in Sweden (Netnod)',
    'PITChile',
    'Seattle Internet Exchange (SIX)',
    'SFMIX',
    'Toronto Internet Exchange (TorIX)'
  ],
  2: [
    'America Movil',
    'AT&T',
    'BT',
    'Colt',
    'C&W Networks',
    'China Telecom',
    'Deutsche Telecom',
    'EUNetworks',
    'Global Cloud Exchange',
    'GTT',
    'KDDI',
    'Level 3',
    'NTT',
    'Orange',
    'PCCW',
    'Softbank Telecom',
    'Tata Communications',
    'Telstra',
    'Turk Telekom',
    'Vodafone',
    'Verizon',
    'Zayo Group'
  ],
  3: [
    'Coresite',
    'Cyxtera',
    'CenturyLink',
    'Digital Realty',
    'Equinix',
    'Flexential',
    'Global Switch',
    'Interxion',
    'Iron Mountain',
    'Macquarie Data Centers',
    'NTT',
    'QTS',
    'ST Telemedia Global Data Centres (STT GDC)',
    'Xfernet',
    'Zayo'
  ]
}
