import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faUserCircle,
  faBell,
  faPen,
  faCog,
  faTimes,
  faStar,
  faBolt,
  faHome,
  faMap,
  faDizzy,
  faCaretDown,
  faCaretUp,
  faSearch,
  faFilter,
  faCartPlus,
  faArrowLeft,
  faExpandArrowsAlt,
  faEllipsisV,
  faChevronUp,
  faCertificate,
  faSignOutAlt,
  faExclamationCircle,
  faShareAlt,
  faHeart,
  faTrash,
  faPlus,
  faBezierCurve,
  faUser,
  faBug,
  faAward,
  faSitemap,
  faProjectDiagram,
  faExclamationTriangle,
  faCloudUploadAlt,
  faBraille
} from '@fortawesome/free-solid-svg-icons'
import {
  faFacebook,
  faTwitter,
  faLinkedin,
  faInstagram
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faAward,
  faBraille,
  faSitemap,
  faProjectDiagram,
  faExclamationTriangle,
  faUserCircle,
  faBell,
  faPen,
  faUser,
  faBug,
  faCog,
  faPlus,
  faBezierCurve,
  faExpandArrowsAlt,
  faCaretUp,
  faCaretDown,
  faTimes,
  faStar,
  faBolt,
  faHome,
  faMap,
  faDizzy,
  faSearch,
  faFilter,
  faCartPlus,
  faArrowLeft,
  faEllipsisV,
  faChevronUp,
  faCertificate,
  faSignOutAlt,
  faFacebook,
  faTwitter,
  faLinkedin,
  faInstagram,
  faShareAlt,
  faHeart,
  faTrash,
  faCloudUploadAlt,
  faExclamationCircle
)

Vue.component('fa', FontAwesomeIcon)
